import {
  Sparkles, Scissors, Mic, Podcast, Image, Megaphone, Mail, Zap, MessageCircle,
  Users, Target, FolderOpen, CheckSquare, FormInput, Vote, Calendar, CalendarClock,
  Trophy, Layout, Shield, PieChart, BarChart3, Instagram, FileText, 
  Video, Radio, Headphones, Clapperboard, Share2, Lightbulb, Newspaper,
  Bot, Wand2, BrainCircuit, Palette, Globe, Briefcase, DollarSign, Building2,
  type LucideIcon
} from "lucide-react";

export interface SeeksyModule {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: string;
  route?: string;
  downloads?: number;
  isNew?: boolean;
  isAIPowered?: boolean;
  integrations?: string[];
  bgGradient?: string;
  iconBg?: string;
  iconColor?: string;
}

export interface ModuleCategory {
  id: string;
  name: string;
  isNew?: boolean;
}

// Integration icons with colors
export const INTEGRATION_ICONS: Record<string, { name: string; icon: string; bg: string }> = {
  slack: { name: "Slack", icon: "S", bg: "bg-[#4A154B]" },
  drive: { name: "Google Drive", icon: "D", bg: "bg-[#4285F4]" },
  zoom: { name: "Zoom", icon: "Z", bg: "bg-[#2D8CFF]" },
  gmail: { name: "Gmail", icon: "G", bg: "bg-[#EA4335]" },
  calendar: { name: "Calendar", icon: "C", bg: "bg-[#4285F4]" },
  spotify: { name: "Spotify", icon: "S", bg: "bg-[#1DB954]" },
  apple: { name: "Apple", icon: "A", bg: "bg-[#555555]" },
  youtube: { name: "YouTube", icon: "Y", bg: "bg-[#FF0000]" },
  instagram: { name: "Instagram", icon: "I", bg: "bg-gradient-to-br from-[#833AB4] via-[#FD1D1D] to-[#FCAF45]" },
  tiktok: { name: "TikTok", icon: "T", bg: "bg-[#000000]" },
  facebook: { name: "Facebook", icon: "F", bg: "bg-[#1877F2]" },
  twitter: { name: "Twitter/X", icon: "X", bg: "bg-[#000000]" },
  linkedin: { name: "LinkedIn", icon: "L", bg: "bg-[#0A66C2]" },
  hubspot: { name: "HubSpot", icon: "H", bg: "bg-[#FF7A59]" },
  stripe: { name: "Stripe", icon: "$", bg: "bg-[#635BFF]" },
  notion: { name: "Notion", icon: "N", bg: "bg-[#000000]" },
  figma: { name: "Figma", icon: "F", bg: "bg-[#F24E1E]" },
  jira: { name: "Jira", icon: "J", bg: "bg-[#0052CC]" },
  asana: { name: "Asana", icon: "A", bg: "bg-[#F06A6A]" },
  trello: { name: "Trello", icon: "T", bg: "bg-[#0079BF]" },
  dropbox: { name: "Dropbox", icon: "D", bg: "bg-[#0061FF]" },
  twilio: { name: "Twilio", icon: "T", bg: "bg-[#F22F46]" },
  resend: { name: "Resend", icon: "R", bg: "bg-[#000000]" },
  cloudflare: { name: "Cloudflare", icon: "C", bg: "bg-[#F38020]" },
  openai: { name: "OpenAI", icon: "O", bg: "bg-[#10A37F]" },
  elevenlabs: { name: "ElevenLabs", icon: "E", bg: "bg-[#000000]" },
};

export const MODULE_CATEGORIES: ModuleCategory[] = [
  { id: "ai-tools", name: "AI Tools", isNew: true },
  { id: "content-production", name: "Content Production" },
  { id: "podcasting", name: "Podcasting" },
  { id: "studio-recording", name: "Studio & Recording" },
  { id: "marketing", name: "Marketing" },
  { id: "crm-contacts", name: "CRM & Contacts" },
  { id: "meetings-events", name: "Meetings & Events" },
  { id: "business-tools", name: "Business Tools" },
  { id: "sales-leads", name: "Sales & Leads" },
  { id: "automation", name: "Automation" },
  { id: "analytics", name: "Analytics" },
  { id: "identity", name: "Identity & Profile" },
];

export const SEEKSY_MODULES: SeeksyModule[] = [
  // AI Tools
  {
    id: "ai-clips",
    name: "AI Clips Generator",
    description: "Automatically generate viral clips from your long-form content with AI-powered detection and scoring",
    icon: Scissors,
    category: "ai-tools",
    route: "/clips",
    downloads: 45200,
    isNew: true,
    isAIPowered: true,
    integrations: ["youtube", "tiktok", "instagram", "cloudflare"],
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-fuchsia-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-600",
  },
  {
    id: "ai-post-production",
    name: "AI Post-Production",
    description: "Remove filler words, pauses, silence, and enhance audio quality automatically with AI",
    icon: Wand2,
    category: "ai-tools",
    route: "/studio/ai-post-production",
    downloads: 38100,
    isAIPowered: true,
    integrations: ["openai", "elevenlabs", "cloudflare"],
    bgGradient: "bg-gradient-to-br from-blue-100 via-cyan-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-600",
  },
  {
    id: "spark-ai",
    name: "Spark AI Assistant",
    description: "Your intelligent AI co-pilot for content ideas, scheduling, and growth strategy",
    icon: BrainCircuit,
    category: "ai-tools",
    route: "/spark",
    downloads: 67800,
    isNew: true,
    isAIPowered: true,
    integrations: ["openai", "calendar", "notion"],
    bgGradient: "bg-gradient-to-br from-amber-100 via-orange-50 to-yellow-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-amber-600",
  },
  // Content Production
  {
    id: "studio",
    name: "Studio & Recording",
    description: "Record podcasts, videos, and livestreams with HD quality, guest invites, and screen sharing",
    icon: Mic,
    category: "studio-recording",
    route: "/studio",
    downloads: 72000,
    integrations: ["zoom", "slack", "drive", "calendar"],
    bgGradient: "bg-gradient-to-br from-rose-100 via-pink-50 to-red-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-rose-600",
  },
  {
    id: "podcasts",
    name: "Podcast Hosting",
    description: "Host your podcast with RSS feeds, analytics, and automatic distribution to all major platforms",
    icon: Podcast,
    category: "podcasting",
    route: "/podcasts",
    downloads: 96300,
    integrations: ["spotify", "apple", "youtube", "instagram"],
    bgGradient: "bg-gradient-to-br from-emerald-100 via-green-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-emerald-600",
  },
  {
    id: "media-library",
    name: "Media Library",
    description: "Store, organize, and manage all your audio, video, and images in one centralized place",
    icon: Image,
    category: "content-production",
    route: "/studio/media",
    downloads: 54200,
    integrations: ["drive", "dropbox", "cloudflare"],
    bgGradient: "bg-gradient-to-br from-sky-100 via-blue-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-sky-600",
  },
  {
    id: "video-editor",
    name: "Video Editor",
    description: "Edit videos with timeline, transitions, captions, and export in multiple formats",
    icon: Clapperboard,
    category: "content-production",
    route: "/studio/editor",
    downloads: 34500,
    integrations: ["cloudflare", "youtube", "drive"],
    bgGradient: "bg-gradient-to-br from-purple-100 via-violet-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-purple-600",
  },
  // Marketing
  {
    id: "campaigns",
    name: "Marketing Campaigns",
    description: "Create, schedule, and design all your marketing content and campaigns in one place",
    icon: Megaphone,
    category: "marketing",
    route: "/marketing/campaigns",
    downloads: 175200,
    integrations: ["gmail", "instagram", "facebook", "hubspot"],
    bgGradient: "bg-gradient-to-br from-orange-100 via-amber-50 to-yellow-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-orange-600",
  },
  {
    id: "email",
    name: "Email Marketing",
    description: "Full email inbox with templates, sequences, automations, and multi-account support",
    icon: Mail,
    category: "marketing",
    route: "/email/inbox",
    downloads: 89400,
    integrations: ["gmail", "resend", "hubspot", "stripe"],
    bgGradient: "bg-gradient-to-br from-red-100 via-rose-50 to-pink-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-red-600",
  },
  {
    id: "sms",
    name: "SMS Marketing",
    description: "Text messaging campaigns with templates, scheduling, and 2-way conversations",
    icon: MessageCircle,
    category: "marketing",
    route: "/sms",
    downloads: 28700,
    integrations: ["twilio", "hubspot"],
    bgGradient: "bg-gradient-to-br from-green-100 via-emerald-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-green-600",
  },
  {
    id: "blog",
    name: "Blog & Content",
    description: "Write and publish blog posts with SEO optimization and content scheduling",
    icon: Newspaper,
    category: "content-production",
    route: "/blog",
    downloads: 67300,
    integrations: ["notion", "drive"],
    bgGradient: "bg-gradient-to-br from-slate-100 via-gray-50 to-zinc-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-slate-700",
  },
  {
    id: "newsletter",
    name: "Newsletter",
    description: "Build and send beautiful newsletters with drag-and-drop editor and subscriber management",
    icon: Share2,
    category: "marketing",
    route: "/newsletter",
    downloads: 45600,
    integrations: ["resend", "gmail", "stripe"],
    bgGradient: "bg-gradient-to-br from-cyan-100 via-sky-50 to-blue-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-cyan-600",
  },
  // CRM & Contacts
  {
    id: "contacts",
    name: "Contacts & Audience",
    description: "Manage contacts, leads, and subscribers with segments, tags, and custom fields",
    icon: Users,
    category: "crm-contacts",
    route: "/audience",
    downloads: 102400,
    integrations: ["hubspot", "gmail", "linkedin", "stripe"],
    bgGradient: "bg-gradient-to-br from-indigo-100 via-blue-50 to-violet-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-indigo-600",
  },
  {
    id: "segments",
    name: "Audience Segments",
    description: "Create targeted audience segments based on behavior, attributes, and engagement",
    icon: Target,
    category: "crm-contacts",
    route: "/marketing/segments",
    downloads: 67800,
    integrations: ["hubspot", "gmail"],
    bgGradient: "bg-gradient-to-br from-pink-100 via-rose-50 to-red-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-pink-600",
  },
  // Sales & Leads
  {
    id: "deals",
    name: "Deals Pipeline",
    description: "Track deals through your sales pipeline with stages, values, and forecasting",
    icon: DollarSign,
    category: "sales-leads",
    route: "/sales/deals",
    downloads: 56200,
    integrations: ["stripe", "hubspot", "slack"],
    bgGradient: "bg-gradient-to-br from-green-100 via-emerald-50 to-lime-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-green-700",
  },
  {
    id: "proposals",
    name: "Proposals & Contracts",
    description: "Create professional proposals with e-signatures and automated follow-ups",
    icon: FileText,
    category: "sales-leads",
    route: "/proposals",
    downloads: 45600,
    integrations: ["stripe", "gmail", "drive"],
    bgGradient: "bg-gradient-to-br from-teal-100 via-cyan-50 to-sky-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-teal-600",
  },
  // Business Tools
  {
    id: "project-management",
    name: "Project Management",
    description: "Manage tasks, tickets, leads, and deadlines with boards, lists, and timeline views",
    icon: FolderOpen,
    category: "business-tools",
    route: "/project-management",
    downloads: 108500,
    integrations: ["jira", "asana", "slack", "notion"],
    bgGradient: "bg-gradient-to-br from-blue-100 via-indigo-50 to-purple-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-700",
  },
  {
    id: "tasks",
    name: "Tasks & To-dos",
    description: "Create and track tasks with due dates, priorities, assignments, and subtasks",
    icon: CheckSquare,
    category: "business-tools",
    route: "/tasks",
    downloads: 84200,
    integrations: ["asana", "trello", "slack"],
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-fuchsia-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-700",
  },
  // Forms
  {
    id: "forms",
    name: "Forms Builder",
    description: "Build forms and collect submissions with custom fields, logic, and file uploads",
    icon: FormInput,
    category: "business-tools",
    route: "/forms",
    downloads: 56700,
    integrations: ["hubspot", "gmail", "slack"],
    bgGradient: "bg-gradient-to-br from-amber-100 via-yellow-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-amber-700",
  },
  {
    id: "polls",
    name: "Polls & Surveys",
    description: "Collect audience feedback with interactive polls, surveys, and voting",
    icon: Vote,
    category: "business-tools",
    route: "/polls",
    downloads: 34500,
    integrations: ["slack", "gmail"],
    bgGradient: "bg-gradient-to-br from-lime-100 via-green-50 to-emerald-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-lime-700",
  },
  // Meetings & Events
  {
    id: "events",
    name: "Events & Ticketing",
    description: "Create events, sell tickets, manage RSVPs, and handle check-ins with QR codes",
    icon: Calendar,
    category: "meetings-events",
    route: "/events",
    downloads: 78300,
    integrations: ["stripe", "calendar", "zoom", "gmail"],
    bgGradient: "bg-gradient-to-br from-fuchsia-100 via-pink-50 to-rose-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-fuchsia-700",
  },
  {
    id: "meetings",
    name: "Meetings & Scheduling",
    description: "Book calls and appointments with calendar integration and automated reminders",
    icon: CalendarClock,
    category: "meetings-events",
    route: "/creator/meetings",
    downloads: 92100,
    integrations: ["calendar", "zoom", "gmail", "slack"],
    bgGradient: "bg-gradient-to-br from-sky-100 via-cyan-50 to-blue-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-sky-700",
  },
  {
    id: "awards",
    name: "Awards Program",
    description: "Create award programs with nominations, voting rounds, and ceremony management",
    icon: Trophy,
    category: "meetings-events",
    route: "/awards",
    downloads: 23400,
    integrations: ["stripe", "gmail"],
    bgGradient: "bg-gradient-to-br from-yellow-100 via-amber-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-yellow-600",
  },
  // Identity & Profile
  {
    id: "my-page",
    name: "My Page Builder",
    description: "Build your personal landing page with drag-and-drop sections and themes",
    icon: Layout,
    category: "identity",
    route: "/profile/edit",
    downloads: 145600,
    integrations: ["instagram", "youtube", "tiktok", "linkedin"],
    bgGradient: "bg-gradient-to-br from-rose-100 via-pink-50 to-fuchsia-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-rose-600",
  },
  {
    id: "identity-verification",
    name: "Identity & Verification",
    description: "Verify your voice and face on blockchain, manage usage rights and permissions",
    icon: Shield,
    category: "identity",
    route: "/identity",
    downloads: 67200,
    isNew: true,
    integrations: ["openai", "cloudflare"],
    bgGradient: "bg-gradient-to-br from-emerald-100 via-teal-50 to-cyan-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-emerald-600",
  },
  // Automation
  {
    id: "automations",
    name: "Workflow Automations",
    description: "Build automated workflows and sequences to save time and scale your operations",
    icon: Zap,
    category: "automation",
    route: "/marketing/automations",
    downloads: 43100,
    integrations: ["slack", "gmail", "hubspot", "stripe"],
    bgGradient: "bg-gradient-to-br from-yellow-100 via-orange-50 to-amber-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-yellow-600",
  },
  {
    id: "ai-automation",
    name: "AI Automation",
    description: "Create intelligent automations powered by AI that learn and adapt",
    icon: Bot,
    category: "automation",
    route: "/automations/ai",
    downloads: 31200,
    isAIPowered: true,
    isNew: true,
    integrations: ["openai", "slack", "gmail"],
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-600",
  },
  // Analytics
  {
    id: "social-analytics",
    name: "Social Analytics",
    description: "Track social media performance across all connected platforms with deep insights",
    icon: PieChart,
    category: "analytics",
    route: "/social-analytics",
    downloads: 134700,
    integrations: ["instagram", "youtube", "tiktok", "facebook"],
    bgGradient: "bg-gradient-to-br from-blue-100 via-indigo-50 to-violet-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-600",
  },
  {
    id: "audience-insights",
    name: "Audience Insights",
    description: "Deep analytics on followers, engagement, demographics, and growth trends",
    icon: BarChart3,
    category: "analytics",
    route: "/social-analytics",
    downloads: 89300,
    integrations: ["instagram", "youtube", "tiktok"],
    bgGradient: "bg-gradient-to-br from-emerald-100 via-green-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-emerald-600",
  },
  {
    id: "social-connect",
    name: "Social Connect",
    description: "Connect Instagram, YouTube, TikTok, Facebook and sync your data automatically",
    icon: Instagram,
    category: "analytics",
    route: "/integrations",
    downloads: 167800,
    integrations: ["instagram", "youtube", "tiktok", "facebook", "twitter"],
    bgGradient: "bg-gradient-to-br from-pink-100 via-rose-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-pink-600",
  },
];

export function formatDownloads(num: number): string {
  if (num >= 1000) {
    return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K';
  }
  return num.toString();
}
