import {
  Sparkles, Scissors, Mic, Podcast, Image, Megaphone, Mail, Zap, MessageCircle,
  Users, Target, FolderOpen, CheckSquare, FormInput, Vote, Calendar, CalendarClock,
  Trophy, Layout, Shield, PieChart, BarChart3, Instagram, FileText, 
  Video, Radio, Headphones, Clapperboard, Share2, Lightbulb, Newspaper,
  Bot, Wand2, BrainCircuit, Palette, Globe, Briefcase, DollarSign, Building2,
  Copy, Eye,
  type LucideIcon
} from "lucide-react";

export interface SeeksyModule {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: string;
  route?: string;
  primaryGroup?: string; // Which group this module belongs to
  isNew?: boolean;
  isAIPowered?: boolean;
  integrations?: string[]; // Now Seeksy module IDs, not external apps
  bgGradient?: string;
  iconBg?: string;
  iconColor?: string;
}

export interface ModuleCategory {
  id: string;
  name: string;
  isNew?: boolean;
}

// Seeksy-native integration icons with colors (module relationships)
export const INTEGRATION_ICONS: Record<string, { name: string; icon: string; bg: string }> = {
  // Seeksy Modules as integrations
  "ai-clips": { name: "AI Clips Generator", icon: "A", bg: "bg-violet-600" },
  "ai-post-production": { name: "AI Post-Production", icon: "P", bg: "bg-blue-600" },
  "podcasts": { name: "Podcasting", icon: "P", bg: "bg-emerald-600" },
  "studio": { name: "Video Studio", icon: "V", bg: "bg-rose-600" },
  "media-library": { name: "Media Library", icon: "M", bg: "bg-sky-600" },
  "video-editor": { name: "Video Editor", icon: "E", bg: "bg-purple-600" },
  "podcast-rss": { name: "Podcast RSS Hosting", icon: "R", bg: "bg-green-600" },
  "cloning": { name: "Voice Cloning", icon: "C", bg: "bg-indigo-600" },
  "email": { name: "Email Client", icon: "E", bg: "bg-red-600" },
  "sms": { name: "SMS Marketing", icon: "S", bg: "bg-green-500" },
  "newsletter": { name: "Newsletter", icon: "N", bg: "bg-cyan-600" },
  "automations": { name: "Automations", icon: "A", bg: "bg-yellow-600" },
  "campaigns": { name: "Campaigns", icon: "C", bg: "bg-orange-600" },
  "contacts": { name: "Contacts", icon: "C", bg: "bg-indigo-500" },
  "crm": { name: "CRM", icon: "C", bg: "bg-blue-700" },
  "meetings": { name: "Meetings", icon: "M", bg: "bg-sky-700" },
  "events": { name: "Events", icon: "E", bg: "bg-fuchsia-600" },
  "forms": { name: "Forms", icon: "F", bg: "bg-amber-600" },
  "polls": { name: "Polls", icon: "P", bg: "bg-lime-600" },
  "awards": { name: "Awards", icon: "A", bg: "bg-yellow-500" },
  "tasks": { name: "Tasks", icon: "T", bg: "bg-violet-700" },
  "projects": { name: "Projects", icon: "P", bg: "bg-blue-800" },
  "proposals": { name: "Proposals", icon: "P", bg: "bg-teal-600" },
  "deals": { name: "Deals", icon: "D", bg: "bg-green-700" },
  "identity": { name: "Identity", icon: "I", bg: "bg-emerald-700" },
  "broadcast-monitoring": { name: "Broadcast Monitoring", icon: "B", bg: "bg-violet-600" },
  "spark-ai": { name: "Spark AI", icon: "S", bg: "bg-amber-500" },
  "blog": { name: "Blog", icon: "B", bg: "bg-slate-600" },
  "social-analytics": { name: "Social Analytics", icon: "S", bg: "bg-blue-500" },
};

export const MODULE_CATEGORIES: ModuleCategory[] = [
  { id: "creator-studio", name: "Creator Studio", isNew: true },
  { id: "podcasting", name: "Podcasting" },
  { id: "campaigns", name: "Campaigns & Marketing" },
  { id: "events", name: "Events & Meetings" },
  { id: "crm-business", name: "CRM & Business Tools" },
  { id: "analytics", name: "Analytics" },
  { id: "identity", name: "Identity & Profile" },
  { id: "ai-tools", name: "AI Tools", isNew: true },
];

// Define module group families
export const MODULE_GROUP_FAMILIES: Record<string, { name: string; icon: LucideIcon; modules: string[] }> = {
  "creator-studio": {
    name: "Creator Studio",
    icon: Mic,
    modules: ["studio", "ai-clips", "ai-post-production", "media-library", "video-editor", "cloning"],
  },
  "podcasting": {
    name: "Podcasting",
    icon: Podcast,
    modules: ["podcasts", "podcast-analytics"],
  },
  "campaigns": {
    name: "Campaigns",
    icon: Megaphone,
    modules: ["campaigns", "email", "newsletter", "automations", "sms"],
  },
  "events": {
    name: "Events",
    icon: Calendar,
    modules: ["events", "meetings", "forms", "polls", "awards"],
  },
  "crm-business": {
    name: "CRM & Business",
    icon: Users,
    modules: ["crm", "contacts", "project-management", "tasks", "proposals", "deals"],
  },
};

export const SEEKSY_MODULES: SeeksyModule[] = [
  // Creator Studio Group
  {
    id: "studio",
    name: "Studio & Recording",
    description: "Record podcasts, videos, and livestreams with HD quality, guest invites, and screen sharing",
    icon: Mic,
    category: "creator-studio",
    route: "/studio",
    primaryGroup: "creator-studio",
    bgGradient: "bg-gradient-to-br from-rose-100 via-pink-50 to-red-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-rose-600",
  },
  {
    id: "ai-clips",
    name: "AI Clips Generator",
    description: "Automatically generate viral clips from your long-form content with AI-powered detection and scoring",
    icon: Scissors,
    category: "creator-studio",
    route: "/clips",
    primaryGroup: "creator-studio",
    isNew: true,
    isAIPowered: true,
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-fuchsia-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-600",
  },
  {
    id: "ai-post-production",
    name: "AI Post-Production",
    description: "Remove filler words, pauses, silence, and enhance audio quality automatically with AI",
    icon: Wand2,
    category: "creator-studio",
    route: "/studio/ai-post-production",
    primaryGroup: "creator-studio",
    isAIPowered: true,
    bgGradient: "bg-gradient-to-br from-blue-100 via-cyan-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-600",
  },
  {
    id: "media-library",
    name: "Media Library",
    description: "Store, organize, and manage all your audio, video, and images in one centralized place",
    icon: Image,
    category: "creator-studio",
    route: "/studio/media",
    primaryGroup: "creator-studio",
    bgGradient: "bg-gradient-to-br from-sky-100 via-blue-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-sky-600",
  },
  {
    id: "video-editor",
    name: "Video Editor",
    description: "Edit videos with timeline, transitions, captions, and export in multiple formats",
    icon: Clapperboard,
    category: "creator-studio",
    route: "/studio/editor",
    primaryGroup: "creator-studio",
    bgGradient: "bg-gradient-to-br from-purple-100 via-violet-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-purple-600",
  },
  {
    id: "cloning",
    name: "Voice Cloning Tools",
    description: "Clone and manage AI voice profiles for content creation and automation",
    icon: Copy,
    category: "creator-studio",
    route: "/voice-cloning",
    primaryGroup: "creator-studio",
    isNew: true,
    isAIPowered: true,
    bgGradient: "bg-gradient-to-br from-indigo-100 via-violet-50 to-purple-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-indigo-600",
  },
  
  // Podcasting Group - just one module "Podcasts" (hosting is built-in)
  {
    id: "podcasts",
    name: "Podcasts",
    description: "Host your podcast with RSS feeds, analytics, and automatic distribution to all major platforms",
    icon: Podcast,
    category: "podcasting",
    route: "/podcasts",
    primaryGroup: "podcasting",
    bgGradient: "bg-gradient-to-br from-emerald-100 via-green-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-emerald-600",
  },
  
  // Campaigns Group
  {
    id: "campaigns",
    name: "Marketing Campaigns",
    description: "Create, schedule, and design all your marketing content and campaigns in one place",
    icon: Megaphone,
    category: "campaigns",
    route: "/marketing/campaigns",
    primaryGroup: "campaigns",
    bgGradient: "bg-gradient-to-br from-orange-100 via-amber-50 to-yellow-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-orange-600",
  },
  {
    id: "email",
    name: "Inbox",
    description: "Full email inbox with templates, sequences, and multi-account support",
    icon: Mail,
    category: "campaigns",
    route: "/email/inbox",
    primaryGroup: "campaigns",
    bgGradient: "bg-gradient-to-br from-red-100 via-rose-50 to-pink-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-red-600",
  },
  {
    id: "newsletter",
    name: "Newsletter",
    description: "Build and send beautiful newsletters with drag-and-drop editor and subscriber management",
    icon: Share2,
    category: "campaigns",
    route: "/newsletter",
    primaryGroup: "campaigns",
    bgGradient: "bg-gradient-to-br from-cyan-100 via-sky-50 to-blue-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-cyan-600",
  },
  {
    id: "sms",
    name: "SMS Marketing",
    description: "Text messaging campaigns with templates, scheduling, and 2-way conversations",
    icon: MessageCircle,
    category: "campaigns",
    route: "/sms",
    primaryGroup: "campaigns",
    bgGradient: "bg-gradient-to-br from-green-100 via-emerald-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-green-600",
  },
  {
    id: "automations",
    name: "Workflow Automations",
    description: "Build automated workflows and sequences to save time and scale your operations",
    icon: Zap,
    category: "campaigns",
    route: "/marketing/automations",
    primaryGroup: "campaigns",
    bgGradient: "bg-gradient-to-br from-yellow-100 via-orange-50 to-amber-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-yellow-600",
  },
  
  // Events Group
  {
    id: "events",
    name: "Events & Ticketing",
    description: "Create events, sell tickets, manage RSVPs, and handle check-ins with QR codes",
    icon: Calendar,
    category: "events",
    route: "/events",
    primaryGroup: "events",
    bgGradient: "bg-gradient-to-br from-fuchsia-100 via-pink-50 to-rose-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-fuchsia-700",
  },
  {
    id: "meetings",
    name: "Meetings & Scheduling",
    description: "Book calls and appointments with calendar integration and automated reminders",
    icon: CalendarClock,
    category: "events",
    route: "/creator/meetings",
    primaryGroup: "events",
    bgGradient: "bg-gradient-to-br from-sky-100 via-cyan-50 to-blue-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-sky-700",
  },
  {
    id: "forms",
    name: "Forms Builder",
    description: "Build forms and collect submissions with custom fields, logic, and file uploads",
    icon: FormInput,
    category: "events",
    route: "/forms",
    primaryGroup: "events",
    bgGradient: "bg-gradient-to-br from-amber-100 via-yellow-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-amber-700",
  },
  {
    id: "polls",
    name: "Polls & Surveys",
    description: "Collect audience feedback with interactive polls, surveys, and voting",
    icon: Vote,
    category: "events",
    route: "/polls",
    primaryGroup: "events",
    bgGradient: "bg-gradient-to-br from-lime-100 via-green-50 to-emerald-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-lime-700",
  },
  {
    id: "awards",
    name: "Awards Program",
    description: "Create award programs with nominations, voting rounds, and ceremony management",
    icon: Trophy,
    category: "events",
    route: "/awards",
    primaryGroup: "events",
    bgGradient: "bg-gradient-to-br from-yellow-100 via-amber-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-yellow-600",
  },
  
  // CRM & Business Group
  {
    id: "crm",
    name: "CRM",
    description: "Complete customer relationship management with deals, activities, and reporting",
    icon: Building2,
    category: "crm-business",
    route: "/crm",
    primaryGroup: "crm-business",
    bgGradient: "bg-gradient-to-br from-blue-100 via-indigo-50 to-violet-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-700",
  },
  {
    id: "contacts",
    name: "Contacts & Audience",
    description: "Manage contacts, leads, and subscribers with segments, tags, and custom fields",
    icon: Users,
    category: "crm-business",
    route: "/audience",
    primaryGroup: "crm-business",
    bgGradient: "bg-gradient-to-br from-indigo-100 via-blue-50 to-violet-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-indigo-600",
  },
  {
    id: "project-management",
    name: "Project Management",
    description: "Manage tasks, tickets, leads, and deadlines with boards, lists, and timeline views",
    icon: FolderOpen,
    category: "crm-business",
    route: "/project-management",
    primaryGroup: "crm-business",
    bgGradient: "bg-gradient-to-br from-blue-100 via-indigo-50 to-purple-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-700",
  },
  {
    id: "tasks",
    name: "Tasks & To-dos",
    description: "Create and track tasks with due dates, priorities, assignments, and subtasks",
    icon: CheckSquare,
    category: "crm-business",
    route: "/tasks",
    primaryGroup: "crm-business",
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-fuchsia-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-700",
  },
  {
    id: "proposals",
    name: "Proposals & Contracts",
    description: "Create professional proposals with e-signatures and automated follow-ups",
    icon: FileText,
    category: "crm-business",
    route: "/proposals",
    primaryGroup: "crm-business",
    bgGradient: "bg-gradient-to-br from-teal-100 via-cyan-50 to-sky-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-teal-600",
  },
  {
    id: "deals",
    name: "Deals Pipeline",
    description: "Track deals through your sales pipeline with stages, values, and forecasting",
    icon: DollarSign,
    category: "crm-business",
    route: "/deals",
    primaryGroup: "crm-business",
    bgGradient: "bg-gradient-to-br from-green-100 via-emerald-50 to-lime-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-green-700",
  },
  
  // Identity & Profile
  {
    id: "my-page",
    name: "My Page Builder",
    description: "Build your personal landing page with drag-and-drop sections and themes",
    icon: Layout,
    category: "identity",
    route: "/profile/edit",
    bgGradient: "bg-gradient-to-br from-rose-100 via-pink-50 to-fuchsia-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-rose-600",
  },
  {
    id: "identity-verification",
    name: "Identity & Verification",
    description: "Verify your voice and face on blockchain, manage usage rights and permissions",
    icon: Shield,
    category: "identity",
    route: "/identity",
    isNew: true,
    bgGradient: "bg-gradient-to-br from-emerald-100 via-teal-50 to-cyan-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-emerald-600",
  },
  {
    id: "broadcast-monitoring",
    name: "Broadcast Monitoring",
    description: "Monitor platforms for unauthorized use of your voice and content with AI-powered detection",
    icon: Eye,
    category: "identity",
    route: "/broadcast-monitoring",
    isNew: true,
    isAIPowered: true,
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-600",
  },
  
  // Content
  {
    id: "blog",
    name: "Blog & Content",
    description: "Write and publish blog posts with SEO optimization and content scheduling",
    icon: Newspaper,
    category: "content",
    route: "/my-blog",
    primaryGroup: "campaigns",
    bgGradient: "bg-gradient-to-br from-slate-100 via-gray-50 to-zinc-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-slate-700",
  },
  
  // AI Tools (standalone)
  {
    id: "spark-ai",
    name: "Spark AI Assistant",
    description: "Your intelligent AI co-pilot for content ideas, scheduling, and growth strategy",
    icon: BrainCircuit,
    category: "ai-tools",
    route: "/spark",
    isNew: true,
    isAIPowered: true,
    bgGradient: "bg-gradient-to-br from-amber-100 via-orange-50 to-yellow-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-amber-600",
  },
  {
    id: "ai-automation",
    name: "AI Automation",
    description: "Create intelligent automations powered by AI that learn and adapt",
    icon: Bot,
    category: "ai-tools",
    route: "/automations/ai",
    isAIPowered: true,
    isNew: true,
    bgGradient: "bg-gradient-to-br from-violet-100 via-purple-50 to-indigo-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-violet-600",
  },
  
  // Analytics
  {
    id: "social-analytics",
    name: "Social Analytics",
    description: "Track social media performance across all connected platforms with deep insights",
    icon: PieChart,
    category: "analytics",
    route: "/social-analytics",
    bgGradient: "bg-gradient-to-br from-blue-100 via-indigo-50 to-violet-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-blue-600",
  },
  {
    id: "audience-insights",
    name: "Audience Insights",
    description: "Deep analytics on followers, engagement, demographics, and growth trends",
    icon: BarChart3,
    category: "analytics",
    route: "/social-analytics",
    bgGradient: "bg-gradient-to-br from-emerald-100 via-green-50 to-teal-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-emerald-600",
  },
  {
    id: "social-connect",
    name: "Social Connect",
    description: "Connect Instagram, YouTube, TikTok, Facebook and sync your data automatically",
    icon: Instagram,
    category: "analytics",
    route: "/integrations",
    bgGradient: "bg-gradient-to-br from-pink-100 via-rose-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-pink-600",
  },
  
  // Audience Segments
  {
    id: "segments",
    name: "Audience Segments",
    description: "Create targeted audience segments based on behavior, attributes, and engagement",
    icon: Target,
    category: "campaigns",
    route: "/marketing/segments",
    bgGradient: "bg-gradient-to-br from-pink-100 via-rose-50 to-red-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-pink-600",
  },
  
  // AI Agent (standalone AI tool)
  {
    id: "ai-agent",
    name: "AI Agent",
    description: "Your intelligent AI co-pilot for content ideas, scheduling, navigation, and growth strategy",
    icon: BrainCircuit,
    category: "ai-tools",
    route: "/assistant",
    isNew: true,
    isAIPowered: true,
    bgGradient: "bg-gradient-to-br from-amber-100 via-yellow-50 to-orange-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-amber-600",
  },
  
  // Email Signatures
  {
    id: "email-signatures",
    name: "Settings",
    description: "Email settings, signatures, and tracking configuration",
    icon: Mail,
    category: "campaigns",
    route: "/signatures",
    isNew: true,
    bgGradient: "bg-gradient-to-br from-indigo-100 via-blue-50 to-cyan-100",
    iconBg: "bg-white shadow-lg",
    iconColor: "text-indigo-600",
  },
];

export function formatDownloads(num: number): string {
  if (num >= 1000) {
    return `${(num / 1000).toFixed(1)}k`;
  }
  return num.toString();
}
