import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useQuery, useMutation } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Card } from "@/components/ui/card";
import { toast } from "sonner";
import { Camera, MapPin, Loader2, X } from "lucide-react";

export default function CreateLead() {
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [location, setLocation] = useState<{ lat: number; lng: number; accuracy: number } | null>(null);
  const [photos, setPhotos] = useState<File[]>([]);
  const [photoPreview, setPhotoPreview] = useState<string[]>([]);

  // Form state
  const [propertyAddress, setPropertyAddress] = useState("");
  const [repName, setRepName] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [phone, setPhone] = useState("");
  const [email, setEmail] = useState("");
  const [preferredContact, setPreferredContact] = useState<string[]>([]);
  const [workTypes, setWorkTypes] = useState<string[]>([]);
  const [leadStatus, setLeadStatus] = useState("");
  const [notes, setNotes] = useState("");
  const [bestContactTimes, setBestContactTimes] = useState<string[]>([]);
  const [customContactTime, setCustomContactTime] = useState("");
  const [estimateTime, setEstimateTime] = useState("");

  const { data: user } = useQuery({
    queryKey: ["user"],
    queryFn: async () => {
      const { data: { user } } = await supabase.auth.getUser();
      return user;
    },
  });

  // Get current location
  useEffect(() => {
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setLocation({
            lat: position.coords.latitude,
            lng: position.coords.longitude,
            accuracy: position.coords.accuracy,
          });
          toast.success("Location captured successfully");
        },
        (error) => {
          console.error("Error getting location:", error);
          toast.error("Unable to get location. Please enable location services.");
        }
      );
    }
  }, []);

  const handlePhotoCapture = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    setPhotos((prev) => [...prev, ...files]);

    // Create preview URLs
    files.forEach((file) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        setPhotoPreview((prev) => [...prev, reader.result as string]);
      };
      reader.readAsDataURL(file);
    });
  };

  const removePhoto = (index: number) => {
    setPhotos((prev) => prev.filter((_, i) => i !== index));
    setPhotoPreview((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      toast.error("You must be logged in");
      return;
    }

    if (!propertyAddress || !firstName || !lastName || !phone) {
      toast.error("Please fill in all required fields");
      return;
    }

    setIsSubmitting(true);

    try {
      // Create or find contact
      const fullName = `${firstName} ${lastName}`;
      const { data: existingContact } = await supabase
        .from("contacts")
        .select("id")
        .eq("email", email || phone)
        .eq("user_id", user.id)
        .single();

      let contactId = existingContact?.id;

      if (!contactId) {
        const { data: newContact, error: contactError } = await supabase
          .from("contacts")
          .insert({
            user_id: user.id,
            name: fullName,
            email: email || null,
            phone: phone,
            company: propertyAddress,
            lead_status: leadStatus || "new",
            lead_source: "Door Knocking - Field Lead",
            notes: notes,
          })
          .select()
          .single();

        if (contactError) throw contactError;
        contactId = newContact.id;
      }

      // Create ticket
      const { data: ticket, error: ticketError } = await supabase
        .from("tickets")
        .insert({
          user_id: user.id,
          ticket_number: '', // Will be auto-generated by trigger
          contact_id: contactId,
          title: `New Lead: ${propertyAddress}`,
          description: notes,
          status: "open",
          priority: leadStatus === "Hot Lead – Homeowner wants estimate ASAP" ? "high" : "medium",
          category: "lead",
          property_address: propertyAddress,
          latitude: location?.lat,
          longitude: location?.lng,
          location_accuracy: location?.accuracy,
          work_types: workTypes,
          preferred_contact_method: preferredContact,
          best_contact_times: [...bestContactTimes, customContactTime].filter(Boolean),
          scheduled_estimate_time: estimateTime,
        })
        .select()
        .single();

      if (ticketError) throw ticketError;

      // Upload photos
      if (photos.length > 0) {
        const uploadPromises = photos.map(async (photo, index) => {
          const fileExt = photo.name.split(".").pop();
          const fileName = `${ticket.id}/${Date.now()}_${index}.${fileExt}`;

          const { error: uploadError, data } = await supabase.storage
            .from("lead-photos")
            .upload(fileName, photo);

          if (uploadError) throw uploadError;

          const { data: { publicUrl } } = supabase.storage
            .from("lead-photos")
            .getPublicUrl(fileName);

          // Save photo record
          await supabase.from("lead_photos").insert({
            ticket_id: ticket.id,
            photo_url: publicUrl,
          });
        });

        await Promise.all(uploadPromises);
      }

      toast.success("Lead created successfully!");
      navigate("/project-management");
    } catch (error: any) {
      console.error("Error creating lead:", error);
      toast.error(error.message || "Failed to create lead");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-background p-4 pb-20">
      <div className="max-w-2xl mx-auto">
        <Card className="p-6">
          <div className="mb-6">
            <h1 className="text-2xl font-bold mb-2">Door-Knocking Lead Sheet</h1>
            <p className="text-muted-foreground">
              Collect property and homeowner information, work requests, lead status, notes, and scheduling details.
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-8">
            {/* Location Status */}
            {location && (
              <div className="flex items-center gap-2 text-sm text-green-600 bg-green-50 dark:bg-green-950 p-3 rounded-lg">
                <MapPin className="h-4 w-4" />
                <span>Location captured (±{location.accuracy.toFixed(0)}m accuracy)</span>
              </div>
            )}

            {/* Section 1: Property Information */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">1. Property Information</h2>
              
              <div>
                <Label htmlFor="propertyAddress">Property Address *</Label>
                <Input
                  id="propertyAddress"
                  value={propertyAddress}
                  onChange={(e) => setPropertyAddress(e.target.value)}
                  required
                />
              </div>

              <div>
                <Label htmlFor="repName">Representative Name *</Label>
                <Input
                  id="repName"
                  value={repName}
                  onChange={(e) => setRepName(e.target.value)}
                  placeholder="Your name"
                  required
                />
              </div>
            </div>

            {/* Section 2: Homeowner Information */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">2. Homeowner Information</h2>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="firstName">First Name *</Label>
                  <Input
                    id="firstName"
                    value={firstName}
                    onChange={(e) => setFirstName(e.target.value)}
                    required
                  />
                </div>
                <div>
                  <Label htmlFor="lastName">Last Name *</Label>
                  <Input
                    id="lastName"
                    value={lastName}
                    onChange={(e) => setLastName(e.target.value)}
                    required
                  />
                </div>
              </div>

              <div>
                <Label htmlFor="phone">Phone Number *</Label>
                <Input
                  id="phone"
                  type="tel"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  placeholder="(000) 000-0000"
                  required
                />
              </div>

              <div>
                <Label htmlFor="email">Email Address</Label>
                <Input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="example@example.com"
                />
              </div>

              <div>
                <Label>Preferred Contact Method *</Label>
                <div className="space-y-2 mt-2">
                  {["Phone", "Text", "Email"].map((method) => (
                    <div key={method} className="flex items-center space-x-2">
                      <Checkbox
                        id={`contact-${method}`}
                        checked={preferredContact.includes(method)}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setPreferredContact([...preferredContact, method]);
                          } else {
                            setPreferredContact(preferredContact.filter((m) => m !== method));
                          }
                        }}
                      />
                      <Label htmlFor={`contact-${method}`} className="font-normal">
                        {method}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Section 3: Type of Work Requested */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">3. Type of Work Requested</h2>
              <p className="text-sm text-muted-foreground">Check all that apply</p>
              
              <div className="space-y-2">
                {[
                  "Stump Grinding",
                  "Tree Removal",
                  "Tree Trimming / Pruning",
                  "Lot Clearing",
                  "Emergency Service",
                  "Other"
                ].map((work) => (
                  <div key={work} className="flex items-center space-x-2">
                    <Checkbox
                      id={`work-${work}`}
                      checked={workTypes.includes(work)}
                      onCheckedChange={(checked) => {
                        if (checked) {
                          setWorkTypes([...workTypes, work]);
                        } else {
                          setWorkTypes(workTypes.filter((w) => w !== work));
                        }
                      }}
                    />
                    <Label htmlFor={`work-${work}`} className="font-normal">
                      {work}
                    </Label>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 4: Lead Status */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">4. Lead Status</h2>
              <p className="text-sm text-muted-foreground">Rep must select one</p>
              
              <RadioGroup value={leadStatus} onValueChange={setLeadStatus}>
                {[
                  "Hot Lead – Homeowner wants estimate ASAP",
                  "Warm Lead – Interested but needs follow-up",
                  "Cold Lead – Not right now, but potential future work",
                  "Not Home – Left door hanger"
                ].map((status) => (
                  <div key={status} className="flex items-center space-x-2">
                    <RadioGroupItem value={status} id={`status-${status}`} />
                    <Label htmlFor={`status-${status}`} className="font-normal">
                      {status}
                    </Label>
                  </div>
                ))}
              </RadioGroup>
            </div>

            {/* Section 5: Notes */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">5. Notes (Icebreakers / Key Details / What Team Should Know)</h2>
              <p className="text-sm text-muted-foreground">
                Examples: Large oak leaning toward roof, Friendly dog named Duke, Said neighbor also needs work
              </p>
              
              <Textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Enter notes and key details..."
                rows={6}
              />
            </div>

            {/* Section 6: Best Time to Contact */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">6. Best Time to Contact</h2>
              
              <div>
                <Label>Preferred time(s) to contact</Label>
                <div className="space-y-2 mt-2">
                  {["Morning", "Afternoon", "Evening"].map((time) => (
                    <div key={time} className="flex items-center space-x-2">
                      <Checkbox
                        id={`time-${time}`}
                        checked={bestContactTimes.includes(time)}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setBestContactTimes([...bestContactTimes, time]);
                          } else {
                            setBestContactTimes(bestContactTimes.filter((t) => t !== time));
                          }
                        }}
                      />
                      <Label htmlFor={`time-${time}`} className="font-normal">
                        {time}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <Label htmlFor="customTime">Other best time to contact (write-in)</Label>
                <Input
                  id="customTime"
                  value={customContactTime}
                  onChange={(e) => setCustomContactTime(e.target.value)}
                  placeholder="e.g., Weekends only, After 6pm"
                />
              </div>
            </div>

            {/* Section 7: Scheduled Estimate */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">7. Scheduled Estimate (if homeowner agreed)</h2>
              
              <div>
                <Label htmlFor="estimateTime">Requested Day or Time Window for Estimate</Label>
                <Input
                  id="estimateTime"
                  value={estimateTime}
                  onChange={(e) => setEstimateTime(e.target.value)}
                  placeholder="e.g., Thursday afternoon, Next week"
                />
              </div>
            </div>

            {/* Photo Upload */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">8. Property Photos</h2>
              
              <div>
                <Label htmlFor="photos" className="cursor-pointer">
                  <div className="border-2 border-dashed border-muted-foreground/25 rounded-lg p-6 text-center hover:border-primary transition-colors">
                    <Camera className="h-12 w-12 mx-auto mb-2 text-muted-foreground" />
                    <p className="text-sm font-medium">Take Photos</p>
                    <p className="text-xs text-muted-foreground">Tap to use camera or select from gallery</p>
                  </div>
                </Label>
                <Input
                  id="photos"
                  type="file"
                  accept="image/*"
                  capture="environment"
                  multiple
                  onChange={handlePhotoCapture}
                  className="hidden"
                />
              </div>

              {photoPreview.length > 0 && (
                <div className="grid grid-cols-2 gap-4">
                  {photoPreview.map((preview, index) => (
                    <div key={index} className="relative">
                      <img
                        src={preview}
                        alt={`Property photo ${index + 1}`}
                        className="w-full h-32 object-cover rounded-lg"
                      />
                      <Button
                        type="button"
                        size="icon"
                        variant="destructive"
                        className="absolute top-2 right-2 h-6 w-6"
                        onClick={() => removePhoto(index)}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Submit */}
            <Button
              type="submit"
              className="w-full h-14 text-lg"
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="h-5 w-5 animate-spin mr-2" />
                  Submitting Lead...
                </>
              ) : (
                "Submit Lead"
              )}
            </Button>
          </form>
        </Card>
      </div>
    </div>
  );
}