import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { CheckCircle2, Loader2, Sparkles, Video, FileText, TrendingUp, Wand2 } from "lucide-react";
import { useEffect, useState } from "react";

interface ProcessingStage {
  id: string;
  label: string;
  icon: any;
  status: 'pending' | 'processing' | 'complete';
  description: string;
}

interface VideoProcessingDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  jobType: 'ai_edit' | 'ad_insertion' | 'full_process';
  onComplete: (analysis: any) => void;
}

export const VideoProcessingDialog = ({ 
  open, 
  onOpenChange, 
  jobType,
  onComplete 
}: VideoProcessingDialogProps) => {
  const [currentStageIndex, setCurrentStageIndex] = useState(0);
  const [progress, setProgress] = useState(0);
  
  const stages: ProcessingStage[] = [
    {
      id: 'loading',
      label: 'Loading Video',
      icon: Video,
      status: 'processing',
      description: 'Analyzing video content and metadata...'
    },
    {
      id: 'transcript',
      label: 'Generating Transcript',
      icon: FileText,
      status: 'pending',
      description: 'AI is transcribing audio with timestamps...'
    },
    {
      id: 'analysis',
      label: 'Analyzing Content',
      icon: Sparkles,
      status: 'pending',
      description: jobType === 'ai_edit' 
        ? "Detecting filler words, pauses, and quality issues..."
        : jobType === 'ad_insertion'
        ? "Finding optimal ad break points..."
        : "Performing comprehensive video analysis..."
    },
    {
      id: 'enhancement',
      label: 'Enhancement Suggestions',
      icon: Wand2,
      status: 'pending',
      description: 'Generating quality improvement recommendations...'
    },
    {
      id: 'optimization',
      label: 'Finalizing',
      icon: TrendingUp,
      status: 'pending',
      description: 'Preparing results and comparison data...'
    }
  ];

  const [processedStages, setProcessedStages] = useState(stages);

  useEffect(() => {
    if (!open) {
      setCurrentStageIndex(0);
      setProgress(0);
      setProcessedStages(stages);
      return;
    }

    // Simulate processing stages
    const timer = setInterval(() => {
      setProgress((prev) => {
        const newProgress = Math.min(prev + 2, 100);
        
        // Update stage status based on progress
        const stageProgress = (newProgress / 100) * stages.length;
        const newStageIndex = Math.floor(stageProgress);
        
        if (newStageIndex !== currentStageIndex && newStageIndex < stages.length) {
          setCurrentStageIndex(newStageIndex);
          setProcessedStages(prev => prev.map((stage, idx) => ({
            ...stage,
            status: idx < newStageIndex ? 'complete' : 
                   idx === newStageIndex ? 'processing' : 'pending'
          })));
        }
        
        // Complete processing
        if (newProgress === 100) {
          setTimeout(() => {
            onComplete({
              transcript: "Sample transcript generated by AI...",
              fillerWords: [
                { word: "um", timestamp: 5.2, duration: 0.3 },
                { word: "uh", timestamp: 12.5, duration: 0.4 },
                { word: "like", timestamp: 28.1, duration: 0.2 }
              ],
              scenes: [
                { start: 0, end: 30, description: "Introduction segment", quality: "good" },
                { start: 30, end: 90, description: "Main content", quality: "good" }
              ],
              suggestedAdBreaks: [
                { timestamp: 30, reason: "Natural scene transition" },
                { timestamp: 90, reason: "Topic change, good engagement point" }
              ],
              qualityIssues: [
                { type: "lighting", timestamp: 45, severity: "medium", suggestion: "Increase brightness and contrast" },
                { type: "audio", timestamp: 70, severity: "low", suggestion: "Slight audio normalization recommended" }
              ]
            });
            onOpenChange(false);
          }, 500);
        }
        
        return newProgress;
      });
    }, 50);

    return () => clearInterval(timer);
  }, [open, currentStageIndex]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary animate-pulse" />
            AI Processing Your Video
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Progress Bar */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">Processing...</span>
              <span className="font-medium">{Math.round(progress)}%</span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>

          {/* Processing Stages */}
          <div className="space-y-3">
            {processedStages.map((stage, idx) => {
              const Icon = stage.icon;
              return (
                <div 
                  key={stage.id}
                  className={`flex items-start gap-3 p-3 rounded-lg transition-all ${
                    stage.status === 'processing' 
                      ? 'bg-primary/10 border border-primary/20' 
                      : stage.status === 'complete'
                      ? 'bg-green-500/10'
                      : 'bg-muted/50'
                  }`}
                >
                  <div className="mt-0.5">
                    {stage.status === 'complete' ? (
                      <CheckCircle2 className="h-5 w-5 text-green-500" />
                    ) : stage.status === 'processing' ? (
                      <Loader2 className="h-5 w-5 text-primary animate-spin" />
                    ) : (
                      <Icon className="h-5 w-5 text-muted-foreground" />
                    )}
                  </div>
                  <div className="flex-1 space-y-1">
                    <div className="flex items-center gap-2">
                      <p className="font-medium text-sm">{stage.label}</p>
                      {stage.status === 'processing' && (
                        <Badge variant="outline" className="text-xs">
                          In Progress
                        </Badge>
                      )}
                      {stage.status === 'complete' && (
                        <Badge variant="default" className="text-xs bg-green-500">
                          Complete
                        </Badge>
                      )}
                    </div>
                    <p className="text-xs text-muted-foreground">
                      {stage.description}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Processing Stats */}
          {progress > 60 && (
            <div className="grid grid-cols-3 gap-3 pt-4 border-t">
              <div className="text-center">
                <p className="text-2xl font-bold text-primary">3</p>
                <p className="text-xs text-muted-foreground">Filler Words</p>
              </div>
              <div className="text-center">
                <p className="text-2xl font-bold text-primary">2</p>
                <p className="text-xs text-muted-foreground">Ad Breaks</p>
              </div>
              <div className="text-center">
                <p className="text-2xl font-bold text-primary">2</p>
                <p className="text-xs text-muted-foreground">Quality Issues</p>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};
