import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Sparkles, Loader2, Copy, Download } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { VisionData, Rock, YearGoal, TractionSliders, Milestone } from '@/hooks/useCEOVTO';
import ReactMarkdown from 'react-markdown';

interface Props {
  vision: VisionData;
  rocks: Rock[];
  yearGoals: YearGoal[];
  sliders: TractionSliders;
  milestones: Milestone[];
  kpis: Record<string, number>;
}

export function AIBriefingSection({ vision, rocks, yearGoals, sliders, milestones, kpis }: Props) {
  const { toast } = useToast();
  const [briefing, setBriefing] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const generateBriefing = async () => {
    setIsGenerating(true);
    try {
      const context = {
        vision: vision.oneYearFocus,
        threeYearPicture: vision.threeYearPicture,
        rocks: rocks.map(r => ({ name: r.name, status: r.status, owner: r.owner })),
        rocksAtRisk: rocks.filter(r => r.status === 'at_risk').map(r => r.name),
        yearGoals: yearGoals.map(g => `${g.label}: ${g.target}`),
        sliders,
        kpis,
        milestones: milestones.filter(m => m.status !== 'completed').map(m => ({ title: m.title, deadline: m.deadline, status: m.status })),
        milestonesAtRisk: milestones.filter(m => m.status === 'at_risk').map(m => m.title),
      };

      const { data, error } = await supabase.functions.invoke('generate-ceo-briefing', {
        body: { context }
      });

      if (error) throw error;
      setBriefing(data?.briefing || 'No briefing generated.');
    } catch (err) {
      console.error('Briefing generation error:', err);
      // Fallback to mock briefing
      setBriefing(generateMockBriefing());
    }
    setIsGenerating(false);
  };

  const generateMockBriefing = () => {
    const rocksAtRisk = rocks.filter(r => r.status === 'at_risk');
    const inProgressRocks = rocks.filter(r => r.status === 'in_progress');
    const upcomingMilestones = milestones.filter(m => m.status !== 'completed').slice(0, 3);

    return `## CEO Board Briefing

### Vision Progress
The company continues to execute on our 1-year focus: "${vision.oneYearFocus.substring(0, 100)}..."

Our key differentiators remain strong, with ${sliders.identityVerification}% identity verification adoption rate.

### KPI Movement Summary
- ARR: $${(kpis.arr / 1000).toFixed(0)}K (${sliders.creatorGrowth}% monthly creator growth)
- Creator Base: ${kpis.creatorCount.toLocaleString()} total, ${kpis.verifiedCreators.toLocaleString()} verified
- AI Tool Adoption: ${kpis.aiToolAdoption}%
- Runway: ${kpis.runway} months at current burn rate

### Rocks Status
- In Progress: ${inProgressRocks.length} rocks actively being worked
${inProgressRocks.map(r => `  - ${r.name} (Owner: ${r.owner})`).join('\n')}

${rocksAtRisk.length > 0 ? `### ⚠️ Risks & Blockers
${rocksAtRisk.map(r => `- ${r.name}: Needs attention from ${r.owner}`).join('\n')}` : '### ✅ No Rocks At Risk\nAll quarterly rocks are on track.'}

### Upcoming Milestones
${upcomingMilestones.map(m => `- ${m.title} — Due: ${new Date(m.deadline).toLocaleDateString()} (${m.status.replace('_', ' ')})`).join('\n')}

### Recommended Next Steps
1. Review advertising demand projections (currently ${sliders.advertisingDemand > 0 ? '+' : ''}${sliders.advertisingDemand}% adjustment)
2. Accelerate identity verification adoption toward 100%
3. Monitor burn rate optimization via AI automation (${sliders.aiAutomation.toFixed(1)}x efficiency)

### 90-Day CEO Priorities
1. Close advertising marketplace v1 launch
2. Secure 2-3 enterprise pilot customers
3. Achieve 25,000 verified creator milestone
4. Prepare board presentation for Q2 review

---
*Generated by Seeksy AI • ${new Date().toLocaleDateString()}*`;
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(briefing);
    toast({ title: 'Copied to clipboard' });
  };

  return (
    <div className="space-y-6">
      <Card className="border-border">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              AI Board Briefing
            </CardTitle>
            <Button onClick={generateBriefing} disabled={isGenerating} className="bg-gradient-to-r from-violet-500 to-purple-600 hover:from-violet-600 hover:to-purple-700">
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  AI Brief the Board
                </>
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {briefing ? (
            <div className="space-y-4">
              <div className="flex justify-end gap-2">
                <Button size="sm" variant="outline" onClick={copyToClipboard}>
                  <Copy className="w-4 h-4 mr-1" /> Copy
                </Button>
              </div>
              <div className="prose prose-sm dark:prose-invert max-w-none p-4 bg-muted/30 rounded-lg border border-border">
                <ReactMarkdown
                  components={{
                    h2: ({ children }) => <h2 className="text-lg font-bold mt-4 mb-2">{children}</h2>,
                    h3: ({ children }) => <h3 className="text-md font-semibold mt-3 mb-1">{children}</h3>,
                    ul: ({ children }) => <ul className="list-disc list-inside space-y-1">{children}</ul>,
                    ol: ({ children }) => <ol className="list-decimal list-inside space-y-1">{children}</ol>,
                    li: ({ children }) => <li className="text-sm">{children}</li>,
                    p: ({ children }) => <p className="text-sm mb-2">{children}</p>,
                    strong: ({ children }) => <strong className="font-semibold">{children}</strong>,
                  }}
                >
                  {briefing}
                </ReactMarkdown>
              </div>
            </div>
          ) : (
            <div className="text-center py-12 text-muted-foreground">
              <Sparkles className="w-12 h-12 mx-auto mb-4 opacity-30" />
              <p>Click "AI Brief the Board" to generate an executive summary</p>
              <p className="text-xs mt-2">Includes vision changes, KPI movement, risks, and recommended next steps</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
