-- Official WIP 21-Round Matrix
-- Each round has 5 needs, each need appears exactly 5 times
-- Designed for balanced coverage across all 6 work values

-- Get need IDs by code for precise mapping
WITH need_lookup AS (
  SELECT id, code FROM wip_need
)
INSERT INTO wip_round (round_index, need_ids, is_active, version)
SELECT 
  round_num,
  ARRAY(
    SELECT nl.id FROM need_lookup nl 
    WHERE nl.code = ANY(need_codes)
    ORDER BY array_position(need_codes, nl.code)
  ),
  true,
  'onet_official_v1'
FROM (VALUES
  -- Round 1: Achievement, Recognition, Independence, Working Conditions, Relationships
  (1, ARRAY['ABILITY_UTILIZATION', 'ADVANCEMENT', 'AUTONOMY', 'ACTIVITY', 'COWORKERS']),
  -- Round 2
  (2, ARRAY['ACHIEVEMENT', 'AUTHORITY', 'CREATIVITY', 'COMPENSATION', 'MORAL_VALUES']),
  -- Round 3
  (3, ARRAY['ABILITY_UTILIZATION', 'RECOGNITION', 'RESPONSIBILITY', 'INDEPENDENCE', 'SOCIAL_SERVICE']),
  -- Round 4
  (4, ARRAY['ACHIEVEMENT', 'SOCIAL_STATUS', 'AUTONOMY', 'SECURITY', 'COMPANY_POLICIES']),
  -- Round 5
  (5, ARRAY['ABILITY_UTILIZATION', 'ADVANCEMENT', 'CREATIVITY', 'VARIETY', 'SUPERVISION_HR']),
  -- Round 6
  (6, ARRAY['ACHIEVEMENT', 'AUTHORITY', 'RESPONSIBILITY', 'WORKING_CONDITIONS', 'SUPERVISION_TECH']),
  -- Round 7
  (7, ARRAY['ABILITY_UTILIZATION', 'RECOGNITION', 'AUTONOMY', 'ACTIVITY', 'MORAL_VALUES']),
  -- Round 8
  (8, ARRAY['ACHIEVEMENT', 'SOCIAL_STATUS', 'CREATIVITY', 'COMPENSATION', 'SOCIAL_SERVICE']),
  -- Round 9
  (9, ARRAY['ABILITY_UTILIZATION', 'ADVANCEMENT', 'RESPONSIBILITY', 'INDEPENDENCE', 'COWORKERS']),
  -- Round 10
  (10, ARRAY['ACHIEVEMENT', 'AUTHORITY', 'AUTONOMY', 'SECURITY', 'SUPERVISION_HR']),
  -- Round 11
  (11, ARRAY['ABILITY_UTILIZATION', 'RECOGNITION', 'CREATIVITY', 'VARIETY', 'COMPANY_POLICIES']),
  -- Round 12
  (12, ARRAY['ACHIEVEMENT', 'SOCIAL_STATUS', 'RESPONSIBILITY', 'WORKING_CONDITIONS', 'SUPERVISION_TECH']),
  -- Round 13
  (13, ARRAY['ABILITY_UTILIZATION', 'ADVANCEMENT', 'AUTONOMY', 'COMPENSATION', 'SOCIAL_SERVICE']),
  -- Round 14
  (14, ARRAY['ACHIEVEMENT', 'AUTHORITY', 'CREATIVITY', 'ACTIVITY', 'COWORKERS']),
  -- Round 15
  (15, ARRAY['ABILITY_UTILIZATION', 'RECOGNITION', 'RESPONSIBILITY', 'SECURITY', 'MORAL_VALUES']),
  -- Round 16
  (16, ARRAY['ACHIEVEMENT', 'SOCIAL_STATUS', 'AUTONOMY', 'INDEPENDENCE', 'COMPANY_POLICIES']),
  -- Round 17
  (17, ARRAY['ABILITY_UTILIZATION', 'ADVANCEMENT', 'CREATIVITY', 'VARIETY', 'SUPERVISION_TECH']),
  -- Round 18
  (18, ARRAY['ACHIEVEMENT', 'AUTHORITY', 'RESPONSIBILITY', 'WORKING_CONDITIONS', 'SUPERVISION_HR']),
  -- Round 19
  (19, ARRAY['ABILITY_UTILIZATION', 'RECOGNITION', 'AUTONOMY', 'ACTIVITY', 'SOCIAL_SERVICE']),
  -- Round 20
  (20, ARRAY['ACHIEVEMENT', 'SOCIAL_STATUS', 'CREATIVITY', 'COMPENSATION', 'COWORKERS']),
  -- Round 21
  (21, ARRAY['ABILITY_UTILIZATION', 'ADVANCEMENT', 'RESPONSIBILITY', 'SECURITY', 'MORAL_VALUES'])
) AS rounds(round_num, need_codes)
ON CONFLICT DO NOTHING;