import { useState } from "react";
import { useCombinedFinancialData } from "@/hooks/useCombinedFinancialData";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { 
  DollarSign, 
  TrendingUp, 
  Download, 
  Loader2,
  BarChart3,
  Target,
  Share2,
  CheckCircle2
} from "lucide-react";
import { 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer,
  Area,
  AreaChart
} from "recharts";
import { CFOAIChat } from "@/components/cfo/CFOAIChat";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import jsPDF from "jspdf";

export default function CombinedFinancialModels() {
  const { toast } = useToast();
  const [showShareModal, setShowShareModal] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [aiScenario, setAiScenario] = useState<"conservative" | "base" | "aggressive">("base");
  
  const getScenarioId = () => {
    return undefined;
  };

  const {
    monthlyProjections,
    yearlySummaries,
    isLoading,
  } = useCombinedFinancialData(getScenarioId());

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value);
  };

  const formatPercentage = (value: number) => {
    return `${value.toFixed(1)}%`;
  };

  const getScenarioMultiplier = (scenario: "conservative" | "base" | "aggressive") => {
    switch (scenario) {
      case "conservative": return 0.75;
      case "aggressive": return 1.35;
      default: return 1.0;
    }
  };

  const getAIScenarioData = () => {
    const multiplier = getScenarioMultiplier(aiScenario);
    return yearlySummaries.map(year => ({
      ...year,
      totalRevenue: year.totalRevenue * multiplier,
      netProfit: year.netProfit * multiplier,
      subscriptionRevenue: year.subscriptionRevenue * multiplier,
      adRevenue: year.adRevenue * multiplier,
    }));
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, 210, 40, "F");
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("Combined 3-Year Revenue Model", 20, 20);
    doc.setFontSize(12);
    doc.text("Subscriptions + Advertising Revenue", 20, 30);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("3-Year Summary", 20, 55);
    
    let yPos = 70;
    yearlySummaries.forEach((year) => {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`Year ${year.year}`, 20, yPos);
      doc.setFont("helvetica", "normal");
      doc.text(`Total Revenue: ${formatCurrency(year.totalRevenue)}`, 30, yPos + 7);
      doc.text(`  Subscriptions: ${formatCurrency(year.subscriptionRevenue)}`, 40, yPos + 14);
      doc.text(`  Ads: ${formatCurrency(year.adRevenue)}`, 40, yPos + 21);
      doc.text(`Net Profit: ${formatCurrency(year.netProfit)}`, 30, yPos + 28);
      doc.text(`Gross Margin: ${formatPercentage(year.grossMargin)}`, 30, yPos + 35);
      yPos += 50;
    });
    
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Seeksy Financial Models | ${new Date().toLocaleDateString()}`,
      20,
      285
    );
    
    doc.save("seeksy-combined-revenue-model.pdf");
    toast({ title: "PDF exported successfully" });
  };

  const handleExportExcel = () => {
    const headers = ["Year", "Subscription Revenue", "Ad Revenue", "Total Revenue", "Total Payouts", "Net Profit", "Gross Margin %"];
    const rows = yearlySummaries.map(year => [
      year.year,
      year.subscriptionRevenue.toFixed(2),
      year.adRevenue.toFixed(2),
      year.totalRevenue.toFixed(2),
      year.totalPayouts.toFixed(2),
      year.netProfit.toFixed(2),
      year.grossMargin.toFixed(2),
    ]);
    
    const csvContent = [headers, ...rows].map(row => row.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "combined-revenue-model.csv";
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Excel file exported successfully" });
  };

  const handleShareWithBoard = async () => {
    setIsSharing(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      const reportData = {
        scenario: aiScenario,
        yearlySummaries: yearlySummaries,
        generatedAt: new Date().toISOString()
      };

      const { error } = await supabase
        .from('board_shared_reports' as any)
        .insert({
          report_type: 'custom_proforma',
          report_name: 'Custom 3-Year Combined Pro Forma',
          report_data: reportData,
          shared_by: user.id,
          is_active: true
        } as any);

      if (error) throw error;

      toast({ 
        title: "Pro Forma shared with Board Portal",
        description: "Board members can now access this report."
      });
      setShowShareModal(false);
    } catch (err) {
      console.error('Share error:', err);
      toast({ 
        title: "Error sharing report", 
        variant: "destructive" 
      });
    } finally {
      setIsSharing(false);
    }
  };

  if (isLoading) {
    return (
      <div className="mx-auto max-w-7xl px-6 py-6 flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  const hasData = yearlySummaries.length > 0 && yearlySummaries.some(y => y.totalRevenue > 0);

  return (
    <div className="mx-auto max-w-7xl px-6 py-6 flex flex-col gap-8 items-stretch">
      {/* Header */}
      <div className="flex flex-col items-start">
        <h1 className="text-3xl font-bold flex items-center gap-2">
          <BarChart3 className="h-8 w-8 text-primary" />
          Combined Revenue Model
        </h1>
        <p className="text-muted-foreground mt-1">
          3-Year projections combining subscription + ad revenue
        </p>
      </div>

      {/* Scenario Toggle Pills */}
      <div className="flex gap-2">
        <Button
          variant={aiScenario === "conservative" ? "default" : "outline"}
          size="sm"
          onClick={() => setAiScenario("conservative")}
        >
          Conservative
        </Button>
        <Button
          variant={aiScenario === "base" ? "default" : "outline"}
          size="sm"
          onClick={() => setAiScenario("base")}
        >
          Base
        </Button>
        <Button
          variant={aiScenario === "aggressive" ? "default" : "outline"}
          size="sm"
          onClick={() => setAiScenario("aggressive")}
        >
          Aggressive
        </Button>
      </div>

      {/* Main Layout: Content + Sticky Spark */}
      <div className="flex gap-8">
        {/* Left Content */}
        <div className="flex-1 space-y-8">
          {/* Two Column Pro Forma Cards */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* AI-Generated Combined Pro Forma */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5" />
                  AI-Generated Combined Pro Forma
                </CardTitle>
                <CardDescription>
                  Market-based projections ({aiScenario} scenario)
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-4">
                  {getAIScenarioData().map((year) => (
                    <div key={year.year} className="p-4 border rounded-lg">
                      <div className="font-bold text-lg mb-2">Year {year.year}</div>
                      <div className="space-y-1 text-sm">
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Total Revenue:</span>
                          <span className="font-medium">{formatCurrency(year.totalRevenue)}</span>
                        </div>
                        <div className="flex justify-between text-xs">
                          <span className="text-muted-foreground pl-4">Subs:</span>
                          <span>{formatCurrency(year.subscriptionRevenue)}</span>
                        </div>
                        <div className="flex justify-between text-xs">
                          <span className="text-muted-foreground pl-4">Ads:</span>
                          <span>{formatCurrency(year.adRevenue)}</span>
                        </div>
                        <div className="flex justify-between pt-2 border-t">
                          <span className="text-muted-foreground">Net Profit:</span>
                          <span className="font-medium">{formatCurrency(year.netProfit)}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="pt-4 space-y-2">
                  <Button variant="outline" size="sm" className="w-full" onClick={handleExportPDF}>
                    <Download className="h-4 w-4 mr-2" />
                    Download PDF
                  </Button>
                  <Button variant="outline" size="sm" className="w-full" onClick={handleExportExcel}>
                    <Download className="h-4 w-4 mr-2" />
                    Download Excel
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Custom 3-Year Combined Pro Forma */}
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="flex items-center gap-2">
                      <Target className="h-5 w-5" />
                      Custom 3-Year Combined Pro Forma
                    </CardTitle>
                    <CardDescription>
                      Based on your custom subscription + ad assumptions
                    </CardDescription>
                  </div>
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => setShowShareModal(true)}
                    className="gap-2"
                  >
                    <Share2 className="h-4 w-4" />
                    Share with Board
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-4">
                  {yearlySummaries.map((year) => (
                    <div key={year.year} className="p-4 border rounded-lg bg-accent/20">
                      <div className="font-bold text-lg mb-2">Year {year.year}</div>
                      <div className="space-y-1 text-sm">
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Total Revenue:</span>
                          <span className="font-medium">{formatCurrency(year.totalRevenue)}</span>
                        </div>
                        <div className="flex justify-between text-xs">
                          <span className="text-muted-foreground pl-4">Subs:</span>
                          <span>{formatCurrency(year.subscriptionRevenue)}</span>
                        </div>
                        <div className="flex justify-between text-xs">
                          <span className="text-muted-foreground pl-4">Ads:</span>
                          <span>{formatCurrency(year.adRevenue)}</span>
                        </div>
                        <div className="flex justify-between pt-2 border-t">
                          <span className="text-muted-foreground">Net Profit:</span>
                          <span className="font-medium">{formatCurrency(year.netProfit)}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-muted-foreground">Gross Margin:</span>
                          <span className="font-medium">{formatPercentage(year.grossMargin)}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Chart */}
                <div className="h-64">
                  <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={yearlySummaries}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis dataKey="year" label={{ value: "Year", position: "insideBottom", offset: -5 }} />
                      <YAxis />
                      <Tooltip 
                        formatter={(value: number) => formatCurrency(value)}
                        labelFormatter={(label) => `Year ${label}`}
                      />
                      <Legend />
                      <Area 
                        type="monotone" 
                        dataKey="subscriptionRevenue" 
                        stackId="1"
                        stroke="#8884d8" 
                        fill="#8884d8" 
                        name="Subscriptions"
                      />
                      <Area 
                        type="monotone" 
                        dataKey="adRevenue" 
                        stackId="1"
                        stroke="#82ca9d" 
                        fill="#82ca9d" 
                        name="Ads"
                      />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>

                <div className="pt-4 space-y-2">
                  <Button variant="outline" size="sm" className="w-full" onClick={handleExportPDF}>
                    <Download className="h-4 w-4 mr-2" />
                    Download PDF
                  </Button>
                  <Button variant="outline" size="sm" className="w-full" onClick={handleExportExcel}>
                    <Download className="h-4 w-4 mr-2" />
                    Download Excel
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Detailed Charts Section */}
          <Card>
            <CardHeader>
              <CardTitle>Monthly Revenue Breakdown</CardTitle>
              <CardDescription>
                36-month detailed projection combining subscription and ad revenue streams
              </CardDescription>
            </CardHeader>
            <CardContent>
              {!hasData ? (
                <div className="h-96 flex flex-col items-center justify-center text-center">
                  <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mb-4">
                    <BarChart3 className="h-8 w-8 text-muted-foreground" />
                  </div>
                  <h3 className="text-lg font-semibold text-foreground mb-2">No Data Available</h3>
                  <p className="text-muted-foreground max-w-sm">
                    Adjust assumptions to generate your custom 3-year model.
                  </p>
                </div>
              ) : (
                <div className="h-96">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={monthlyProjections}>
                      <CartesianGrid strokeDasharray="3 3" />
                      <XAxis 
                        dataKey="periodLabel" 
                        label={{ value: "Month", position: "insideBottom", offset: -5 }}
                      />
                    <YAxis />
                    <Tooltip 
                      formatter={(value: number) => formatCurrency(value)}
                    />
                    <Legend />
                    <Line 
                      type="monotone" 
                      dataKey="subscriptionRevenue" 
                      stroke="#8884d8" 
                      name="Subscription Revenue"
                      dot={false}
                    />
                    <Line 
                      type="monotone" 
                      dataKey="adRevenue" 
                      stroke="#82ca9d" 
                      name="Ad Revenue"
                      dot={false}
                    />
                    <Line 
                      type="monotone" 
                      dataKey="totalRevenue" 
                      stroke="#ffc658" 
                      strokeWidth={2}
                      name="Total Revenue"
                      dot={false}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Right: Sticky Ask Spark */}
        <div className="w-[340px] flex-shrink-0">
          <div className="sticky top-20">
            <Card className="flex flex-col h-[calc(100vh-120px)]">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2">
                  <DollarSign className="h-5 w-5" />
                  Ask Spark (Combined)
                </CardTitle>
                <CardDescription>
                  Ask about combined revenue, margins, and growth projections
                </CardDescription>
              </CardHeader>
              <CardContent className="flex-1 overflow-hidden">
                <div className="mb-4 p-3 bg-muted rounded-lg text-sm text-muted-foreground">
                  <p className="mb-2 font-medium">Example questions:</p>
                  <ul className="space-y-1 text-xs">
                    <li>• "What's our total revenue in Year 2?"</li>
                    <li>• "How much comes from advertising vs subs?"</li>
                    <li>• "What's our net profit growth YoY?"</li>
                  </ul>
                </div>
                <CFOAIChat />
              </CardContent>
            </Card>
          </div>
        </div>
      </div>

      {/* Share with Board Modal */}
      <Dialog open={showShareModal} onOpenChange={setShowShareModal}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <div className="flex items-center gap-2 mb-2">
              <Badge className="bg-blue-100 text-blue-700">BOARD PORTAL</Badge>
            </div>
            <DialogTitle>Share with Board Portal (Internal)</DialogTitle>
            <DialogDescription>
              Grant board members access to this custom 3-year pro forma inside the Board Portal.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <div className="bg-muted/50 rounded-lg p-4 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Report Type:</span>
                <span className="font-medium">Custom 3-Year Pro Forma</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Scenario:</span>
                <span className="font-medium capitalize">{aiScenario}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Access:</span>
                <span className="font-medium">Board Members Only</span>
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowShareModal(false)}>
              Cancel
            </Button>
            <Button onClick={handleShareWithBoard} disabled={isSharing}>
              {isSharing ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <CheckCircle2 className="h-4 w-4 mr-2" />
              )}
              Share with Board
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}